version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mkdir build
      - cp index.html /var/www/html
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files: '**/*'
  discard-paths: yes
